variables:
  DISCORD_WEBHOOK: 'https://discord.com/api/webhooks/1116567519004733540/4x9K_xxPeb2SvXW7aOs4lPQuBTsMh_0hVprgU374CcAIgiTu0LbBnZYTWT7ZGSo6h1fk'
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2
  DOCKER_REGISTRY: 590774876296.dkr.ecr.ap-southeast-1.amazonaws.com
  DOCKER_TLS_CERTDIR: ''
  TAG_LATEST: 590774876296.dkr.ecr.ap-southeast-1.amazonaws.com/pinex:latest
  TAG_COMMIT: 590774876296.dkr.ecr.ap-southeast-1.amazonaws.com/pinex:$CI_COMMIT_SHORT_SHA

include:
  template: SAST.gitlab-ci.yml

workflow:
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
      when: always

stages:
  - test-lint
  - build
  - deploy
  - notification

lint-test-job: # This job also runs in the test stage.
  stage: test-lint # It can run at the same time as unit-test-job (in parallel).
  image: node:18
  script:
    - yarn
    - yarn lint
  cache:
    paths:
      - node_modules

publish-job:
  stage: build
  image:
    name: docker:latest
  services:
    - docker:dind
  before_script:
    - apk add --no-cache python3 py3-pip
    - pip3 install --no-cache-dir awscli
  script:
    - aws ecr get-login-password --region ap-southeast-1 | docker login --username AWS --password-stdin $DOCKER_REGISTRY
    - docker build --cache-from $TAG_LATEST -t $TAG_COMMIT -t $TAG_LATEST .
    - docker push $TAG_COMMIT
    - docker push $TAG_LATEST
