export const enum USERTYPE {
  NEW = 'NEW',
  PRO = 'PRO',
  VSD_PENDING = 'VSD_PENDING',
  VSD_REJECTED = 'VSD_REJECTED',
  EKYC = 'EKYC',
  VSD = 'VSD',
  LOGIN = 'LOGIN',
  NOTLOGIN = 'NOTLOGIN',
  ACTIVE = 'ACTIVE',
  PENDING_TO_CLOSE = 'PENDING_TO_CLOSE',
}
